### ISSUE TITLE
Add another util method to have the color exported as an object

### ISSUE THREAD

**Issue by allocenx** [ilariaventurini/colors-convert#3]
For instance, if i already have a color of hsl type, it will be really useful to have another util method which lets me convert it to an object, as hex2hsl does for instance.

Thank you again!

**Comment by ilariaventurini** [comment]
Hi, I didn't understand what format you would have in input. A string? In which format? 

Something like these?

- `322°, 79%, 52%` -> `{ h: 322, s: 79, l: 52 }`
- `hsl(322°, 79%, 52%)` -> `{ h: 322, s: 79, l: 52 }`

Could you give me an example of what you expected?
Thank you!

**Comment by allocenx** [comment]
> Hi, I didn't understand what format you would have in input. A string? In which format?
> 
> Something like these?
> 
> * `322°, 79%, 52%` -> `{ h: 322, s: 79, l: 52 }`
> * `hsl(322°, 79%, 52%)` -> `{ h: 322, s: 79, l: 52 }`
> 
> Could you give me an example of what you expected?
> Thank you!

Hey there, yep, like both inputs.

**Comment by ilariaventurini** [comment]
Hi @allocenx, my [last commit](https://github.com/ilariaventurini/colors-convert/commit/9f4bd884cc2e2532c5ae3419859c6153478a38c5) solve this issue
